
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Feb 07 09:09:30 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INCREMENT = 32;
  public static final int CHAR = 48;
  public static final int CONST = 22;
  public static final int NAMESPACE = 38;
  public static final int NOT_EQUAL = 19;
  public static final int CONTINUE = 44;
  public static final int LPAREN = 24;
  public static final int GREATER = 34;
  public static final int DECREMENT = 40;
  public static final int FOR = 5;
  public static final int MINUS = 17;
  public static final int STATIC = 7;
  public static final int RPAREN = 6;
  public static final int GT_EQUAL = 18;
  public static final int SEMICOLON = 10;
  public static final int AND = 23;
  public static final int OR = 45;
  public static final int BOOL = 49;
  public static final int COMMA = 8;
  public static final int CLASS = 39;
  public static final int LESSER = 26;
  public static final int PLUS = 4;
  public static final int MAIN = 2;
  public static final int IF = 15;
  public static final int EOF = 0;
  public static final int RETURN = 43;
  public static final int EQUAL = 25;
  public static final int NEW = 12;
  public static final int error = 1;
  public static final int NUMBER = 46;
  public static final int IDENT = 47;
  public static final int BREAK = 28;
  public static final int VOID = 21;
  public static final int MODULE = 31;
  public static final int LT_EQUAL = 35;
  public static final int COLON = 3;
  public static final int LBRACE = 29;
  public static final int ELSE = 14;
  public static final int STOP = 20;
  public static final int LSQUARE = 27;
  public static final int READ = 30;
  public static final int RSQUARE = 42;
  public static final int RBRACE = 13;
  public static final int PROG = 41;
  public static final int EXTENDS = 11;
  public static final int POINTER = 16;
  public static final int DIVISION = 33;
  public static final int OP_EQUAL = 9;
  public static final int MULTIPLICATION = 36;
  public static final int PRINT = 37;
}

